/**
 * Seed curated Piko routes (idempotent upsert by slug).
 *   node backend/scripts/seed-routes.js
 *
 * 27 real, well-known trails across 14 countries. Geometry is a deterministic
 * generated polyline from the trailhead so every route draws on the map before
 * real OSM/GPX data is wired in (mirrors the standalone sandbox seed exactly).
 */
require('dotenv').config();
const mongoose = require('mongoose');
const { connectDB } = require('../config/db.config');
const Route = require('../models/route.model');

// Trailhead coordinates [lat, lng] keyed by slug.
const COORDS = {
  'morskie-oko': [49.262, 20.108], giewont: [49.272, 19.981], koscieliska: [49.273, 19.87],
  'path-of-the-gods': [40.638, 14.565], 'tre-cime': [46.617, 12.295], 'cinque-terre-blue': [44.146, 9.654],
  'calanques-cassis': [43.215, 5.539], 'verdon-blanc-martel': [43.793, 6.367], 'caminito-del-rey': [36.908, -4.794],
  'montserrat-sant-jeroni': [41.594, 1.838], 'eiger-trail': [46.577, 8.02], 'five-lakes-zermatt': [46.02, 7.78],
  'adlerweg-tyrol': [47.408, 11.475], 'partnach-gorge': [47.477, 11.118], 'zugspitze-hollental': [47.477, 11.022],
  trolltunga: [60.124, 6.741], preikestolen: [58.988, 6.136], 'arthurs-seat': [55.944, -3.162],
  'old-man-storr': [57.507, -6.18], reykjadalur: [64.022, -21.222], 'levada-25-fontes': [32.759, -17.131],
  'angels-landing': [37.259, -112.951], 'bright-angel': [36.057, -112.144], 'bear-mountain-loop': [41.312, -73.988],
  'six-glaciers': [51.417, -116.218], 'grouse-grind': [49.37, -123.082], 'nevado-toluca': [19.108, -99.758],
  // Australia
  'bondi-coogee': [-33.891, 151.277], 'uluru-base': [-25.345, 131.032], 'three-sisters-katoomba': [-33.732, 150.312],
  'wineglass-bay': [-42.152, 148.294], 'kings-canyon-rim': [-24.263, 131.569], 'twelve-apostles-walk': [-38.662, 143.104],
  'whitehaven-hill-inlet': [-20.282, 149.039], 'cradle-dove-lake': [-41.658, 145.958], 'royal-coast-track': [-34.076, 151.163],
  'noosa-coastal-walk': [-26.383, 153.106],
  // Austria
  'hallstatt-skywalk': [47.562, 13.649], 'schafberg-wolfgangsee': [47.777, 13.434], 'innsbruck-nordkette': [47.286, 11.393],
  'grossglockner-kaiser-franz': [47.074, 12.751], 'krimml-waterfalls': [47.213, 12.172], 'ahornboden-eng': [47.404, 11.564],
  'wachau-heritage-trail': [48.364, 15.415], 'gosausee-dachstein': [47.53, 13.596], 'dachstein-five-fingers': [47.463, 13.615],
  'salzburg-kapuzinerberg': [47.801, 13.051],
  // United States
  'yosemite-mist-trail': [37.732, -119.558], 'emerald-lake-rockies': [40.31, -105.645], 'delicate-arch': [38.735, -109.499],
  'grand-prismatic-overlook': [44.525, -110.838], 'acadia-ocean-path': [44.323, -68.19], 'multnomah-falls': [45.576, -122.115],
  'rainier-skyline-trail': [46.786, -121.735], 'diamond-head-summit': [21.256, -157.805], 'horseshoe-bend': [36.879, -111.51],
  'franconia-ridge-loop': [44.142, -71.645],
  // Switzerland
  'lauterbrunnen-valley-walk': [46.593, 7.909], oeschinensee: [46.499, 7.725], 'harder-kulm': [46.694, 7.868],
  'creux-du-van': [46.931, 6.735], 'aletsch-panorama': [46.386, 8.078], 'first-bachalpsee': [46.659, 8.053],
  'gornergrat-riffelsee': [45.983, 7.751], 'ebenalp-seealpsee': [47.283, 9.398], 'lavaux-terraces': [46.492, 6.739],
  'rigi-panorama-trail': [47.056, 8.485],
  // France
  'mont-saint-michel-bay': [48.636, -1.511], 'etretat-cliffs': [49.706, 0.192], 'cirque-de-gavarnie': [42.696, -0.011],
  'annecy-lakeside': [45.899, 6.128], 'chamonix-lac-blanc': [45.98, 6.885], 'colorado-provencal': [43.911, 5.492],
  'dune-du-pilat': [44.589, -1.215], 'puy-de-dome': [45.772, 2.964], 'cap-frehel-douaniers': [48.685, -2.318],
  'camargue-flamingo-trail': [43.52, 4.404],
  // Latvia
  'gauja-sigulda': [57.153, 24.85], 'kemeri-bog-boardwalk': [56.917, 23.49], 'jurmala-beach-walk': [56.972, 23.796],
  'cape-kolka': [57.757, 22.594], 'slitere-lighthouse-trail': [57.63, 22.29], 'ligatne-nature-trails': [57.236, 25.043],
  'daugavas-loki': [55.878, 26.75], 'rundale-gardens': [56.414, 24.025], 'kuldiga-ventas-rumba': [56.967, 21.977],
  'amata-river-trail': [57.256, 25.267],
  // Belgium
  'hallerbos-bluebells': [50.72, 4.275], 'hoge-kempen': [50.996, 5.633], 'ninglinspo-valley': [50.472, 5.702],
  'tombeau-du-geant': [49.848, 5.037], 'hautes-fagnes-boardwalk': [50.56, 6.09], 'bruges-canal-walk': [51.209, 3.226],
  'dinant-citadel-meuse': [50.261, 4.912], 'zwin-nature-park': [51.361, 3.36], 'sonian-forest': [50.767, 4.42],
  'durbuy-ourthe-trail': [50.353, 5.456],
  // Norway
  'besseggen-ridge': [61.508, 8.766], romsdalseggen: [62.567, 7.687], galdhopiggen: [61.636, 8.313],
  'lofoten-reinebringen': [67.929, 13.078], 'geiranger-skagefla': [62.101, 7.096], aurlandsdalen: [60.905, 7.187],
  kjeragbolten: [59.034, 6.593], 'dovrefjell-snohetta': [62.319, 9.526], 'senja-segla': [69.501, 17.552],
  'flam-brekkefossen': [60.863, 7.112],
  // United Kingdom
  'scafell-pike': [54.454, -3.211], 'snowdon-llanberis': [53.068, -4.076], 'ben-nevis-track': [56.797, -5.003],
  'seven-sisters-cliffs': [50.749, 0.152], 'giants-causeway-path': [55.24, -6.511], 'cat-bells-keswick': [54.568, -3.17],
  'quiraing-skye': [57.643, -6.266], 'malham-cove': [54.072, -2.158], 'durdle-door-coast': [50.621, -2.277],
  'hadrians-wall-housesteads': [55.013, -2.331],
};

// Bump when seed content changes (photos, copy, …) so existing databases
// refresh on the next boot via ensureCuratedRoutes().
const SEED_VERSION = 3;

// Real photographs of each place (Wikipedia/Wikimedia Commons lead images,
// every URL verified reachable at seed-authoring time).
const PHOTOS = {
  'morskie-oko': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Morskie_Oko_08_VIII_2004-0015.jpg/1280px-Morskie_Oko_08_VIII_2004-0015.jpg',
  giewont: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Giewont_T58.jpg/1280px-Giewont_T58.jpg',
  koscieliska: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Brama_Kraszewskiego_2.jpg/1280px-Brama_Kraszewskiego_2.jpg',
  'path-of-the-gods': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Amalfi_Coast_%28Italy%2C_October_2020%29_-_75_%2850558355441%29.jpg/1280px-Amalfi_Coast_%28Italy%2C_October_2020%29_-_75_%2850558355441%29.jpg',
  'tre-cime': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/2019_Tre_Cime.jpg/1280px-2019_Tre_Cime.jpg',
  'cinque-terre-blue': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Cinque_Terre_%28Italy%2C_October_2020%29_-_24_%2850543603956%29.jpg/1280px-Cinque_Terre_%28Italy%2C_October_2020%29_-_24_%2850543603956%29.jpg',
  'calanques-cassis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Sugiton_-_panoramio_%281%29.jpg/1280px-Sugiton_-_panoramio_%281%29.jpg',
  'verdon-blanc-martel': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Verdon_Gorge_1.jpg/1280px-Verdon_Gorge_1.jpg',
  'caminito-del-rey': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Caminito_del_Rey_3.jpg/1280px-Caminito_del_Rey_3.jpg',
  'montserrat-sant-jeroni': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Montserrat_des_de_Manresa.JPG/1280px-Montserrat_des_de_Manresa.JPG',
  'eiger-trail': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/North_face.jpg/1280px-North_face.jpg',
  'five-lakes-zermatt': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Matterhorn_from_Domh%C3%BCtte_-_2.jpg/1280px-Matterhorn_from_Domh%C3%BCtte_-_2.jpg',
  'adlerweg-tyrol': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Karwendel.JPG/1280px-Karwendel.JPG',
  'partnach-gorge': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Partnachklamm.jpg/1280px-Partnachklamm.jpg',
  'zugspitze-hollental': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Zugspitze_2.JPG/3840px-Zugspitze_2.JPG',
  trolltunga: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Trolltunga_2017.jpg/3840px-Trolltunga_2017.jpg',
  preikestolen: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Lyse_Fjord_et_Preikestolen.jpg/3840px-Lyse_Fjord_et_Preikestolen.jpg',
  'arthurs-seat': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Arthur%27s_Seat%2C_Edinburgh.JPG/3840px-Arthur%27s_Seat%2C_Edinburgh.JPG',
  'old-man-storr': 'https://upload.wikimedia.org/wikipedia/commons/b/b4/The_Storr_by_Grinner.jpg',
  reykjadalur: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Hveragerdi10.JPG',
  'levada-25-fontes': 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Levada_Madeira.jpg',
  'angels-landing': 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Angels_Landing_-_Zion_Canyon.jpg',
  'bright-angel': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Grand_Canyon_National_Park_-_South_-_03.jpg/3840px-Grand_Canyon_National_Park_-_South_-_03.jpg',
  'bear-mountain-loop': 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Bear_Mountain%2C_Hudson_Highlands%2C_New_York.jpg',
  'six-glaciers': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Lake_Louise_17092005.jpg/1280px-Lake_Louise_17092005.jpg',
  'grouse-grind': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Grouse_Mountain_Gondola.JPG',
  'nevado-toluca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Vista_del_Nevado_de_Toluca.jpg/3840px-Vista_del_Nevado_de_Toluca.jpg',
  // Expansion pack — Wikipedia lead images, every URL fetched and verified
  // at authoring time. Slugs without an entry fall back to the scenic pool.
  'bondi-coogee': 'https://upload.wikimedia.org/wikipedia/commons/7/79/Bondi_from_above.jpg',
  'uluru-base': 'https://upload.wikimedia.org/wikipedia/commons/a/a8/ULURU.jpg',
  'three-sisters-katoomba': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Three_Sisters_from_echo_point.jpg/1920px-Three_Sisters_from_echo_point.jpg',
  'wineglass-bay': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Wineglass_Bay_view_from_the_Beach.jpg/3840px-Wineglass_Bay_view_from_the_Beach.jpg',
  'kings-canyon-rim': 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Kings_Canyon_NT_view.jpg',
  'twelve-apostles-walk': 'https://upload.wikimedia.org/wikipedia/commons/e/e4/The_Twelve_Apostles_2011.jpg',
  'whitehaven-hill-inlet': 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Whitehaven_Beach%2C_Whitsunday_Island%2C_Queensland.jpg',
  'cradle-dove-lake': 'https://upload.wikimedia.org/wikipedia/commons/6/67/Dove-Lake_from_South-2008.jpg',
  'royal-coast-track': 'https://upload.wikimedia.org/wikipedia/commons/4/44/Late_Afternoon_at_North_%26_South_Era.jpg',
  'noosa-coastal-walk': 'https://upload.wikimedia.org/wikipedia/commons/0/04/Noosa_head-raffi_kojian-CIMG6549.JPG',
  'hallstatt-skywalk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Hallstatt_-_Zentrum_.JPG/3840px-Hallstatt_-_Zentrum_.JPG',
  'innsbruck-nordkette': 'https://upload.wikimedia.org/wikipedia/commons/0/00/Mandlspitze.jpg',
  'grossglockner-kaiser-franz': 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Gro%C3%9Fglockner_from_behind_the_glass_panorama_tower.JPG',
  'krimml-waterfalls': 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Austrian.waterfall.at.krimml.arp.jpg',
  'wachau-heritage-trail': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Wachau_%282%29.JPG/3840px-Wachau_%282%29.JPG',
  'salzburg-kapuzinerberg': 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Kapuzinerberg.jpg',
  'yosemite-mist-trail': 'https://upload.wikimedia.org/wikipedia/commons/6/65/Mist_trail_1983.jpg',
  'delicate-arch': 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Delicate_arch_sunset.jpg',
  'grand-prismatic-overlook': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Aerial_image_of_Grand_Prismatic_Spring_%28view_from_the_south%29.jpg/3840px-Aerial_image_of_Grand_Prismatic_Spring_%28view_from_the_south%29.jpg',
  'acadia-ocean-path': 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Acadia_National_Park_02.JPG',
  'multnomah-falls': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Multnomah_Falls_on_2_August_2012.jpg/3840px-Multnomah_Falls_on_2_August_2012.jpg',
  'rainier-skyline-trail': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Rainier20200906.jpg/3840px-Rainier20200906.jpg',
  'diamond-head-summit': 'https://upload.wikimedia.org/wikipedia/commons/9/93/Diamond_Head_Hawaii_From_Round_Top_Rd.JPG',
  'horseshoe-bend': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Grand_Canyon_Horseshoe_Bend.jpg/3840px-Grand_Canyon_Horseshoe_Bend.jpg',
  'franconia-ridge-loop': 'https://upload.wikimedia.org/wikipedia/commons/b/b2/AT_-_Franconia_Ridge.JPG',
  'lauterbrunnen-valley-walk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/1_lauterbrunnen_valley_wengen_2022.jpg/3840px-1_lauterbrunnen_valley_wengen_2022.jpg',
  oeschinensee: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/20190725_Oeschinensee-Panorama%2C_Kandersteg_%2806540-42_stitch%29.jpg/3840px-20190725_Oeschinensee-Panorama%2C_Kandersteg_%2806540-42_stitch%29.jpg',
  'harder-kulm': 'https://upload.wikimedia.org/wikipedia/commons/d/d8/14_Harder_Kulm_Lac_Thoune_Photo_by_Giles_Laurent.jpg',
  'creux-du-van': 'https://upload.wikimedia.org/wikipedia/commons/1/14/Creux_du_Van.jpg',
  'aletsch-panorama': 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Switzerland%2C_Bettmeralp_%2819505442736%29.jpg',
  'first-bachalpsee': 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Bachalpsee_reflection.jpg',
  'gornergrat-riffelsee': 'https://upload.wikimedia.org/wikipedia/commons/1/15/Riffelsee_1.jpg',
  'lavaux-terraces': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Lavaux_Switzerland.jpg/3840px-Lavaux_Switzerland.jpg',
  'rigi-panorama-trail': 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Lauerzersee.jpg',
  'mont-saint-michel-bay': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Mont-Saint-Michel_vu_du_ciel.jpg/3840px-Mont-Saint-Michel_vu_du_ciel.jpg',
  'etretat-cliffs': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Vue_d%27%C3%89tretat.jpg/3840px-Vue_d%27%C3%89tretat.jpg',
  'cirque-de-gavarnie': 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Cirque_de_Gavarnie-Photochrom-Restored.jpg',
  'annecy-lakeside': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Boat_%40_Compagnie_des_Bateaux_du_Lac_d%27Annecy_%40_Lake_Annecy_%40_Saint-Jorioz_%2850488289926%29.jpg/3840px-Boat_%40_Compagnie_des_Bateaux_du_Lac_d%27Annecy_%40_Lake_Annecy_%40_Saint-Jorioz_%2850488289926%29.jpg',
  'dune-du-pilat': 'https://upload.wikimedia.org/wikipedia/commons/d/d4/DunePyla.JPG',
  'puy-de-dome': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Aerial_image_of_Puy_de_D%C3%B4me_%28view_from_the_west%29.jpg/3840px-Aerial_image_of_Puy_de_D%C3%B4me_%28view_from_the_west%29.jpg',
  'cap-frehel-douaniers': 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Cap_Frehel_cliffs_w_stereo.jpg',
  'gauja-sigulda': 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Ergeljuklintis424aug037qg.jpg',
  'kemeri-bog-boardwalk': 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Liela_Kemeru_taka_5jul03.JPG',
  'cape-kolka': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Kolkas_rags.jpg/3840px-Kolkas_rags.jpg',
  'slitere-lighthouse-trail': 'https://upload.wikimedia.org/wikipedia/commons/6/66/Latvia%2C_Sl%C4%ABtere_National_Park.jpg',
  'rundale-gardens': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rundale_Palace_%286483271573%29.jpg/3840px-Rundale_Palace_%286483271573%29.jpg',
  'kuldiga-ventas-rumba': 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Ventas_rumba%2C_13.05.2012.jpg',
  'hallerbos-bluebells': 'https://upload.wikimedia.org/wikipedia/commons/9/96/Hallerbos20070421.jpg',
  'hoge-kempen': 'https://upload.wikimedia.org/wikipedia/commons/6/61/Mechelse_Hei_050806.JPG',
  'ninglinspo-valley': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Ninglinspo_-_Aywaille_310714_%283%29.JPG/3840px-Ninglinspo_-_Aywaille_310714_%283%29.JPG',
  'hautes-fagnes-boardwalk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Fagne_Tirifaye_with_the_Hill_river_in_Waimes%2C_Belgium_%28DSCF3682%29.jpg/3840px-Fagne_Tirifaye_with_the_Hill_river_in_Waimes%2C_Belgium_%28DSCF3682%29.jpg',
  'bruges-canal-walk': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Br%C3%BCgge_Blick_vom_Belfried_4.jpg/3840px-Br%C3%BCgge_Blick_vom_Belfried_4.jpg',
  'dinant-citadel-meuse': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Dinant_reflected.jpg/3840px-Dinant_reflected.jpg',
  'zwin-nature-park': 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Zwin.jpg',
  'sonian-forest': 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Autumn_light_in_the_Sonian_Forest.jpg',
  'durbuy-ourthe-trail': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Durbuy_vu_du_jardin_de_l%27anticlinal.jpg/3840px-Durbuy_vu_du_jardin_de_l%27anticlinal.jpg',
  galdhopiggen: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Galdh%C3%B8piggenFromFannar%C3%A5ki.jpg',
  'lofoten-reinebringen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Reine_at_Reinefjorden%2C_2010_September.jpg/3840px-Reine_at_Reinefjorden%2C_2010_September.jpg',
  'geiranger-skagefla': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Geirangerfjord_.jpg/3840px-Geirangerfjord_.jpg',
  kjeragbolten: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Kjerakbolten_Freddy_Fish.jpg',
  'dovrefjell-snohetta': 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Snohetta.jpg',
  'flam-brekkefossen': 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Aurlandsfjorden_fr%C3%A5_Sn%C3%B8vegen.jpg',
  'scafell-pike': 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Scafell_massif.jpg',
  'snowdon-llanberis': 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Snowdon_massif.jpg',
  'ben-nevis-track': 'https://upload.wikimedia.org/wikipedia/commons/0/09/BenNevis2005.jpg',
  'seven-sisters-cliffs': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Coastguard_Cottages_-_view_towards_the_Seven_Sisters_-_geograph.org.uk_-_6833312.jpg/3840px-Coastguard_Cottages_-_view_towards_the_Seven_Sisters_-_geograph.org.uk_-_6833312.jpg',
  'giants-causeway-path': 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Causeway-code_poet-4.jpg',
  'cat-bells-keswick': 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Cat_Bells_and_Friars_Crag.jpg',
  'quiraing-skye': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/North_over_the_Quiraing%2C_Isle_of_Skye.jpg/3840px-North_over_the_Quiraing%2C_Isle_of_Skye.jpg',
  'malham-cove': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Malham_Cove_Yorkshire_Dales.jpg/3840px-Malham_Cove_Yorkshire_Dales.jpg',
  'durdle-door-coast': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Durdle_Door_Overview.jpg/3840px-Durdle_Door_Overview.jpg',
};

const IMG = [
  'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1426604966848-d7adac402bff?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1444090542259-0af8fa96557e?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&q=80&w=1200',
  'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&q=80&w=1200',
];
const img = (i) => [IMG[i % IMG.length], IMG[(i + 5) % IMG.length]];

// Deterministic trail-shape polyline from a trailhead [lat, lng] (GeoJSON [lng, lat]).
function makeLine([lat, lng], seedStr) {
  let h = 2166136261;
  for (let i = 0; i < seedStr.length; i++) h = Math.imul(h ^ seedStr.charCodeAt(i), 16777619) >>> 0;
  const rand = () => { h = (Math.imul(h, 1664525) + 1013904223) >>> 0; return h / 4294967296; };
  const pts = [[lng, lat]];
  let clng = lng, clat = lat;
  for (let i = 0; i < 13; i++) {
    clng += (rand() - 0.45) * 0.004;
    clat += (rand() - 0.4) * 0.004;
    pts.push([Number(clng.toFixed(5)), Number(clat.toFixed(5))]);
  }
  return { type: 'LineString', coordinates: pts };
}

const SEEDS = [
  { id: 'morskie-oko', title: 'Morskie Oko', country: 'Poland', location: 'Tatra National Park · Poland', description: 'The classic walk to Poland’s most famous glacial lake, on a steady well-surfaced road through the valley to the "Eye of the Sea". Reachable by bus from Zakopane.', difficulty: 'easy', distanceKm: 9.5, elevationGainM: 430, estimatedDurationMins: 150, tags: ['Lake', 'Public Transport', 'Family', 'Group Friendly'], ecoScore: 94, weatherScore: 88, accessibilityScore: 82, transport: 'Bus from Zakopane', co2: 1.1, greener: ['Cycle the valley road', 'Shared minibus'] },
  { id: 'giewont', title: 'Giewont', country: 'Poland', location: 'Zakopane · Poland', description: 'Zakopane’s iconic "Sleeping Knight", topped by a 15-metre summit cross. A demanding climb from Kuźnice with a chained final section near the top.', difficulty: 'hard', distanceKm: 11.2, elevationGainM: 935, estimatedDurationMins: 300, tags: ['Summit', 'Iconic', 'Challenging', 'Views'], ecoScore: 90, weatherScore: 66, accessibilityScore: 38, transport: 'Bus to Kuźnice', co2: 0.9, greener: ['Walk in from Zakopane centre'] },
  { id: 'koscieliska', title: 'Kościeliska Valley', country: 'Poland', location: 'Tatra National Park · Poland', description: 'A gentle, scenic valley walk past limestone cliffs and meadows. Mostly flat and stroller-friendly, one of the most accessible routes in the Tatras.', difficulty: 'easy', distanceKm: 8.0, elevationGainM: 150, estimatedDurationMins: 140, tags: ['Valley', 'Accessible', 'Family', 'Group Friendly'], ecoScore: 96, weatherScore: 90, accessibilityScore: 92, transport: 'Bus to Kiry', co2: 1.0, greener: ['Cycle from Zakopane'] },
  { id: 'path-of-the-gods', title: 'Path of the Gods', country: 'Italy', location: 'Amalfi Coast · Italy', description: 'The Sentiero degli Dei traverses high above the Amalfi Coast, with dizzying views over the Tyrrhenian Sea, terraced vineyards and the isle of Capri.', difficulty: 'moderate', distanceKm: 7.8, elevationGainM: 500, estimatedDurationMins: 180, tags: ['Coastal', 'Views', 'Iconic', 'Group Friendly'], ecoScore: 91, weatherScore: 86, accessibilityScore: 45, transport: 'SITA bus to Bomerano', co2: 1.0, greener: ['Ferry + bus combo'] },
  { id: 'tre-cime', title: 'Tre Cime di Lavaredo Loop', country: 'Italy', location: 'Dolomites · Italy', description: 'A loop around the three unmistakable peaks of the Dolomites, past alpine refuges and war-history tunnels. Big scenery for a moderate effort.', difficulty: 'moderate', distanceKm: 10.0, elevationGainM: 400, estimatedDurationMins: 210, tags: ['Dolomites', 'Loop', 'Views', 'Group Friendly'], ecoScore: 88, weatherScore: 80, accessibilityScore: 50, transport: 'Bus to Auronzo refuge', co2: 1.4, greener: ['Shared shuttle from Misurina'] },
  { id: 'cinque-terre-blue', title: 'Cinque Terre Blue Trail', country: 'Italy', location: 'Cinque Terre · Italy', description: 'The coastal path linking the five pastel fishing villages, hopping between harbours, vineyards and clifftops. Easily broken up using the regional train.', difficulty: 'easy', distanceKm: 11.0, elevationGainM: 500, estimatedDurationMins: 240, tags: ['Coastal', 'Villages', 'Public Transport', 'Group Friendly'], ecoScore: 90, weatherScore: 85, accessibilityScore: 40, transport: 'Regional train', co2: 0.6, greener: ['Train hop between villages'] },
  { id: 'calanques-cassis', title: 'Calanques de Cassis', country: 'France', location: 'Calanques NP · France', description: 'A rugged coastal walk from Cassis to the turquoise inlets of En-Vau and Port-Pin, framed by white limestone cliffs and pine. Reachable by bus from Marseille.', difficulty: 'moderate', distanceKm: 9.0, elevationGainM: 350, estimatedDurationMins: 195, tags: ['Coastal', 'Cliffs', 'Views', 'Group Friendly'], ecoScore: 89, weatherScore: 82, accessibilityScore: 35, transport: 'Bus from Marseille', co2: 0.9, greener: ['Boat shuttle to calanque'] },
  { id: 'verdon-blanc-martel', title: 'Gorges du Verdon: Blanc-Martel', country: 'France', location: 'Verdon Gorge · France', description: 'Europe’s grandest canyon on the famous Blanc-Martel trail, through tunnels (bring a torch), ladders and emerald pools far below the rim.', difficulty: 'hard', distanceKm: 14.0, elevationGainM: 700, estimatedDurationMins: 330, tags: ['Canyon', 'Challenging', 'Views'], ecoScore: 85, weatherScore: 76, accessibilityScore: 28, transport: 'Navette shuttle bus', co2: 1.2, greener: ['Seasonal shuttle navette'] },
  { id: 'caminito-del-rey', title: 'Caminito del Rey', country: 'Spain', location: 'El Chorro · Spain', description: 'The restored "King’s Little Path" clings to a sheer gorge wall on boardwalks 100 m above the river. A one-way, ticketed route reachable by train.', difficulty: 'moderate', distanceKm: 7.7, elevationGainM: 250, estimatedDurationMins: 150, tags: ['Gorge', 'Walkway', 'Iconic', 'Public Transport'], ecoScore: 90, weatherScore: 88, accessibilityScore: 48, transport: 'Train to El Chorro', co2: 0.7, greener: ['Walk back to station'] },
  { id: 'montserrat-sant-jeroni', title: 'Montserrat: Sant Jeroni', country: 'Spain', location: 'Montserrat · Spain', description: 'A climb to the highest point of the serrated Montserrat massif, with views over Catalonia and the famous monastery. Reachable by train and rack railway.', difficulty: 'moderate', distanceKm: 8.5, elevationGainM: 600, estimatedDurationMins: 210, tags: ['Summit', 'Monastery', 'Views', 'Group Friendly'], ecoScore: 89, weatherScore: 84, accessibilityScore: 42, transport: 'Train + rack railway', co2: 0.8, greener: ['Cremallera rack railway'] },
  { id: 'eiger-trail', title: 'Eiger Trail', country: 'Switzerland', location: 'Grindelwald · Switzerland', description: 'A dramatic path running directly beneath the Eiger North Face, from Eigergletscher down to Alpiglen. Pure alpine theatre, reachable entirely by train.', difficulty: 'moderate', distanceKm: 6.0, elevationGainM: 250, estimatedDurationMins: 165, tags: ['Alpine', 'Views', 'Iconic', 'Public Transport'], ecoScore: 92, weatherScore: 78, accessibilityScore: 40, transport: 'Train to Eigergletscher', co2: 0.5, greener: ['Cog railway both ways'] },
  { id: 'five-lakes-zermatt', title: 'Five Lakes Walk', country: 'Switzerland', location: 'Zermatt · Switzerland', description: 'The 5-Seenweg links five alpine lakes above Zermatt, three of which mirror the Matterhorn on a still day. Accessed by cable car from the car-free village.', difficulty: 'moderate', distanceKm: 9.3, elevationGainM: 600, estimatedDurationMins: 240, tags: ['Lakes', 'Alpine', 'Views', 'Group Friendly'], ecoScore: 90, weatherScore: 80, accessibilityScore: 45, transport: 'Train + cable car', co2: 0.6, greener: ['Car-free Zermatt access'] },
  { id: 'adlerweg-tyrol', title: 'Eagle Walk: Karwendel Stage', country: 'Austria', location: 'Tyrol · Austria', description: 'A signature stage of Tyrol’s Adlerweg through the Karwendel range, with limestone walls, high pastures and a classic mountain hut for lunch.', difficulty: 'moderate', distanceKm: 12.0, elevationGainM: 700, estimatedDurationMins: 300, tags: ['Alpine', 'Long Distance', 'Views'], ecoScore: 88, weatherScore: 75, accessibilityScore: 40, transport: 'Train to Tyrol valley', co2: 0.7, greener: ['Postbus to trailhead'] },
  { id: 'partnach-gorge', title: 'Partnach Gorge', country: 'Germany', location: 'Garmisch · Germany', description: 'A short, spectacular walk through a deep gorge carved by the Partnach, past waterfalls and ice formations. Family-friendly and reachable by train.', difficulty: 'easy', distanceKm: 4.5, elevationGainM: 120, estimatedDurationMins: 90, tags: ['Gorge', 'Family', 'Accessible', 'Group Friendly'], ecoScore: 93, weatherScore: 88, accessibilityScore: 70, transport: 'Train to Garmisch', co2: 0.6, greener: ['Walk in from the ski stadium'] },
  { id: 'zugspitze-hollental', title: 'Zugspitze via Höllental', country: 'Germany', location: 'Bavarian Alps · Germany', description: 'A serious, exposed ascent of Germany’s highest peak through the Höllental, with a via-ferrata section and a glacier crossing. For experienced hikers only.', difficulty: 'hard', distanceKm: 21.0, elevationGainM: 2200, estimatedDurationMins: 600, tags: ['Summit', 'Alpine', 'Challenging'], ecoScore: 83, weatherScore: 60, accessibilityScore: 20, transport: 'Train to Hammersbach', co2: 0.9, greener: ['Descend by cog railway'] },
  { id: 'trolltunga', title: 'Trolltunga', country: 'Norway', location: 'Odda · Norway', description: 'The "Troll’s Tongue" juts out 700 m above Lake Ringedalsvatnet. A long, strenuous day for one of the most jaw-dropping viewpoints in Scandinavia.', difficulty: 'hard', distanceKm: 28.0, elevationGainM: 1200, estimatedDurationMins: 600, tags: ['Cliff', 'Iconic', 'Challenging', 'Views'], ecoScore: 86, weatherScore: 62, accessibilityScore: 22, transport: 'Bus to Skjeggedal', co2: 1.3, greener: ['Shuttle bus to upper car park'] },
  { id: 'preikestolen', title: 'Preikestolen', country: 'Norway', location: 'Stavanger · Norway', description: 'The flat-topped Pulpit Rock towers 600 m above the Lysefjord. A well-built, hugely popular trail reachable by ferry and bus from Stavanger.', difficulty: 'moderate', distanceKm: 8.0, elevationGainM: 500, estimatedDurationMins: 210, tags: ['Cliff', 'Iconic', 'Views', 'Group Friendly'], ecoScore: 89, weatherScore: 78, accessibilityScore: 45, transport: 'Ferry + bus', co2: 1.0, greener: ['Public ferry from Stavanger'] },
  { id: 'arthurs-seat', title: 'Arthur’s Seat', country: 'United Kingdom', location: 'Edinburgh · Scotland', description: 'An extinct volcano rising straight out of central Edinburgh, with a short climb to a 360° view over the city and the Firth of Forth. Walkable from the centre.', difficulty: 'easy', distanceKm: 4.0, elevationGainM: 250, estimatedDurationMins: 90, tags: ['City', 'Views', 'Public Transport', 'Group Friendly'], ecoScore: 95, weatherScore: 80, accessibilityScore: 65, transport: 'Walk from city centre', co2: 0.2, greener: ['Zero-emission city walk'] },
  { id: 'old-man-storr', title: 'Old Man of Storr', country: 'United Kingdom', location: 'Isle of Skye · Scotland', description: 'A steep pull up to the surreal rock pinnacles of the Storr, with the Sound of Raasay glittering below. One of Skye’s most photographed landscapes.', difficulty: 'moderate', distanceKm: 5.5, elevationGainM: 320, estimatedDurationMins: 150, tags: ['Iconic', 'Views', 'Coastal'], ecoScore: 88, weatherScore: 70, accessibilityScore: 45, transport: 'Bus from Portree', co2: 0.9, greener: ['Stagecoach bus to trailhead'] },
  { id: 'reykjadalur', title: 'Reykjadalur Hot Spring', country: 'Iceland', location: 'Hveragerði · Iceland', description: 'A walk up a steaming geothermal valley to a warm river you can bathe in. Bubbling mud pots and fumaroles line the way. An easy day trip from Reykjavík.', difficulty: 'moderate', distanceKm: 7.0, elevationGainM: 300, estimatedDurationMins: 180, tags: ['Hot Spring', 'Geothermal', 'Views', 'Group Friendly'], ecoScore: 90, weatherScore: 70, accessibilityScore: 45, transport: 'Bus from Reykjavík', co2: 1.1, greener: ['Shared bus tour'] },
  { id: 'levada-25-fontes', title: 'Levada das 25 Fontes', country: 'Portugal', location: 'Madeira · Portugal', description: 'A gentle level walk along a historic irrigation channel through Madeira’s laurel forest to a green amphitheatre fed by 25 springs and waterfalls.', difficulty: 'easy', distanceKm: 9.0, elevationGainM: 200, estimatedDurationMins: 180, tags: ['Levada', 'Waterfalls', 'Family', 'Group Friendly'], ecoScore: 91, weatherScore: 86, accessibilityScore: 60, transport: 'Bus from Funchal', co2: 1.0, greener: ['Shared transfer from Funchal'] },
  { id: 'angels-landing', title: 'Angels Landing', country: 'United States', location: 'Zion NP, Utah · USA', description: 'A thrilling, chain-assisted climb to a narrow fin of rock high above Zion Canyon. Permit required; reached on the park’s free shuttle.', difficulty: 'hard', distanceKm: 8.7, elevationGainM: 460, estimatedDurationMins: 240, tags: ['Iconic', 'Cliff', 'Challenging', 'Views'], ecoScore: 80, weatherScore: 82, accessibilityScore: 25, transport: 'Park shuttle', co2: 0.8, greener: ['Zion electric shuttle'] },
  { id: 'bright-angel', title: 'Bright Angel Trail', country: 'United States', location: 'Grand Canyon, Arizona · USA', description: 'The Grand Canyon’s classic descent below the South Rim, switchbacking past Indian Garden. Turn around early — the climb out is the hard part.', difficulty: 'hard', distanceKm: 19.0, elevationGainM: 1340, estimatedDurationMins: 420, tags: ['Canyon', 'Iconic', 'Challenging'], ecoScore: 78, weatherScore: 85, accessibilityScore: 30, transport: 'Park shuttle', co2: 0.9, greener: ['Rim shuttle bus'] },
  { id: 'bear-mountain-loop', title: 'Bear Mountain Loop', country: 'United States', location: 'Hudson Valley, NY · USA', description: 'A rewarding loop above the Hudson River with views to the Manhattan skyline on clear days. A popular car-free escape reachable by train from the city.', difficulty: 'moderate', distanceKm: 6.5, elevationGainM: 350, estimatedDurationMins: 180, tags: ['Views', 'Forest', 'Public Transport', 'Group Friendly'], ecoScore: 86, weatherScore: 80, accessibilityScore: 55, transport: 'Train + trailhead bus', co2: 1.2, greener: ['Metro-North + bus'] },
  { id: 'six-glaciers', title: 'Plain of Six Glaciers', country: 'Canada', location: 'Banff, Alberta · Canada', description: 'From the turquoise shore of Lake Louise up toward the glaciers of Mount Victoria, finishing at a historic backcountry tea house. Iconic Rockies scenery.', difficulty: 'moderate', distanceKm: 13.8, elevationGainM: 600, estimatedDurationMins: 300, tags: ['Alpine', 'Glacier', 'Tea House', 'Views'], ecoScore: 88, weatherScore: 76, accessibilityScore: 45, transport: 'Park shuttle to Lake Louise', co2: 1.0, greener: ['Parks Canada shuttle'] },
  { id: 'grouse-grind', title: 'Grouse Grind', country: 'Canada', location: 'Vancouver, BC · Canada', description: 'Vancouver’s "Mother Nature’s Stairmaster" — a relentless 2.9 km climb up Grouse Mountain. Ride the gondola back down. Reachable by city bus.', difficulty: 'hard', distanceKm: 2.9, elevationGainM: 850, estimatedDurationMins: 120, tags: ['Steep', 'Fitness', 'Iconic', 'Public Transport'], ecoScore: 84, weatherScore: 78, accessibilityScore: 30, transport: 'Bus from Vancouver', co2: 0.5, greener: ['SeaBus + bus combo'] },
  { id: 'nevado-toluca', title: 'Nevado de Toluca', country: 'Mexico', location: 'Toluca · Mexico', description: 'A high-altitude trek into the crater of an extinct volcano, ringed by jagged peaks and two sacred crater lakes — the Sun and the Moon. Acclimatise first.', difficulty: 'hard', distanceKm: 8.0, elevationGainM: 700, estimatedDurationMins: 240, tags: ['Volcano', 'Crater Lakes', 'Alpine'], ecoScore: 82, weatherScore: 68, accessibilityScore: 25, transport: 'Shared van from Toluca', co2: 1.3, greener: ['Group colectivo van'] },

  // ── Australia ──────────────────────────────────────────────────────────
  { id: 'bondi-coogee', title: 'Bondi to Coogee Coastal Walk', country: 'Australia', location: 'Sydney, NSW · Australia', description: 'Sydney’s classic clifftop walk linking six beaches, with ocean pools, sculpture headlands and whale-watching lookouts along the way.', difficulty: 'easy', distanceKm: 6.0, elevationGainM: 180, estimatedDurationMins: 120, tags: ['Coastal', 'Beaches', 'Public Transport', 'Family'], ecoScore: 92, weatherScore: 90, accessibilityScore: 85, transport: 'Sydney bus/train to Bondi', co2: 0.4, greener: ['Train + bus combo'] },
  { id: 'uluru-base', title: 'Uluru Base Walk', country: 'Australia', location: 'Uluru-Kata Tjuta NP · Australia', description: 'A flat loop around the base of the sacred monolith, past waterholes, rock art and ever-changing red-rock faces. Start at dawn to beat the heat.', difficulty: 'easy', distanceKm: 10.6, elevationGainM: 50, estimatedDurationMins: 210, tags: ['Desert', 'Cultural', 'Iconic', 'Loop'], ecoScore: 88, weatherScore: 70, accessibilityScore: 75, transport: 'Resort shuttle from Yulara', co2: 1.8, greener: ['Cycle the base path'] },
  { id: 'three-sisters-katoomba', title: 'Three Sisters & Giant Stairway', country: 'Australia', location: 'Blue Mountains, NSW · Australia', description: 'From Echo Point down the 900-step Giant Stairway into the eucalyptus rainforest of the Jamison Valley, beneath the famous sandstone sisters.', difficulty: 'moderate', distanceKm: 4.5, elevationGainM: 300, estimatedDurationMins: 150, tags: ['Lookout', 'Rainforest', 'Public Transport', 'Iconic'], ecoScore: 90, weatherScore: 82, accessibilityScore: 55, transport: 'Train to Katoomba', co2: 0.7, greener: ['Blue Mountains rail line'] },
  { id: 'wineglass-bay', title: 'Wineglass Bay Lookout & Beach', country: 'Australia', location: 'Freycinet NP, Tasmania · Australia', description: 'A saddle climb to one of the world’s most photographed bays, then down to its perfect white crescent of sand between pink granite peaks.', difficulty: 'moderate', distanceKm: 6.0, elevationGainM: 300, estimatedDurationMins: 150, tags: ['Beach', 'Lookout', 'Granite', 'Views'], ecoScore: 91, weatherScore: 78, accessibilityScore: 50, transport: 'Drive/shuttle to Freycinet', co2: 2.0, greener: ['Shared shuttle from Coles Bay'] },
  { id: 'kings-canyon-rim', title: 'Kings Canyon Rim Walk', country: 'Australia', location: 'Watarrka NP, NT · Australia', description: 'A red-rock rim circuit above 100-metre sandstone walls, through the beehive domes of the Lost City and down into the palm-filled Garden of Eden.', difficulty: 'moderate', distanceKm: 6.0, elevationGainM: 250, estimatedDurationMins: 210, tags: ['Canyon', 'Desert', 'Loop', 'Views'], ecoScore: 86, weatherScore: 68, accessibilityScore: 40, transport: 'Drive from Kings Creek', co2: 2.4, greener: ['Join a group tour vehicle'] },
  { id: 'twelve-apostles-walk', title: 'Twelve Apostles Clifftop Walk', country: 'Australia', location: 'Great Ocean Road, VIC · Australia', description: 'Boardwalks and clifftop paths above the Southern Ocean’s crumbling limestone stacks — golden at sunset, thunderous in a storm.', difficulty: 'easy', distanceKm: 3.0, elevationGainM: 60, estimatedDurationMins: 75, tags: ['Coastal', 'Iconic', 'Family', 'Sunset'], ecoScore: 89, weatherScore: 75, accessibilityScore: 88, transport: 'V/Line coach via Port Campbell', co2: 1.5, greener: ['Coach along the Great Ocean Road'] },
  { id: 'whitehaven-hill-inlet', title: 'Whitehaven Beach & Hill Inlet', country: 'Australia', location: 'Whitsunday Island, QLD · Australia', description: 'A short forest climb to the Hill Inlet lookout, where swirling tides paint the silica sand and turquoise water into shifting patterns.', difficulty: 'easy', distanceKm: 2.0, elevationGainM: 100, estimatedDurationMins: 60, tags: ['Beach', 'Island', 'Lookout', 'Snorkelling'], ecoScore: 85, weatherScore: 88, accessibilityScore: 45, transport: 'Boat from Airlie Beach', co2: 3.0, greener: ['Sailing tour instead of powerboat'] },
  { id: 'cradle-dove-lake', title: 'Dove Lake Circuit', country: 'Australia', location: 'Cradle Mountain, Tasmania · Australia', description: 'A gentle boardwalk loop beneath Cradle Mountain’s jagged crown, through ancient rainforest of the aptly named Ballroom Forest.', difficulty: 'easy', distanceKm: 6.0, elevationGainM: 150, estimatedDurationMins: 120, tags: ['Lake', 'Loop', 'Rainforest', 'Family'], ecoScore: 93, weatherScore: 65, accessibilityScore: 80, transport: 'Park shuttle bus', co2: 1.2, greener: ['Mandatory park shuttle'] },
  { id: 'royal-coast-track', title: 'Royal National Park Coast Track (Wedding Cake Rock)', country: 'Australia', location: 'Royal NP, NSW · Australia', description: 'The famous stretch of Australia’s oldest national park: sea cliffs, wildflower heath and the impossibly white slab of Wedding Cake Rock.', difficulty: 'moderate', distanceKm: 8.0, elevationGainM: 200, estimatedDurationMins: 180, tags: ['Coastal', 'Cliffs', 'Public Transport', 'Views'], ecoScore: 90, weatherScore: 85, accessibilityScore: 60, transport: 'Train + ferry to Bundeena', co2: 0.5, greener: ['Cronulla ferry crossing'] },
  { id: 'noosa-coastal-walk', title: 'Noosa National Park Coastal Walk', country: 'Australia', location: 'Noosa, QLD · Australia', description: 'An easy subtropical path around Noosa’s headland — koalas in the gums, surfers at Tea Tree Bay and dolphins off Hell’s Gates.', difficulty: 'easy', distanceKm: 10.8, elevationGainM: 150, estimatedDurationMins: 180, tags: ['Coastal', 'Wildlife', 'Family', 'Surf'], ecoScore: 92, weatherScore: 90, accessibilityScore: 78, transport: 'Bus from Noosa Heads', co2: 0.4, greener: ['Walk in from Hastings Street'] },

  // ── Austria ────────────────────────────────────────────────────────────
  { id: 'hallstatt-skywalk', title: 'Hallstatt Skywalk & Salt Mountain', country: 'Austria', location: 'Hallstatt, Salzkammergut · Austria', description: 'Climb (or ride the funicular) above the postcard lakeside village to the World Heritage Skywalk platform, 350 metres over Lake Hallstatt.', difficulty: 'moderate', distanceKm: 5.0, elevationGainM: 350, estimatedDurationMins: 150, tags: ['Lake', 'Village', 'Lookout', 'Heritage'], ecoScore: 90, weatherScore: 78, accessibilityScore: 70, transport: 'Train + ferry to Hallstatt', co2: 0.6, greener: ['Rail via Attnang-Puchheim'] },
  { id: 'schafberg-wolfgangsee', title: 'Schafberg Summit Trail', country: 'Austria', location: 'St. Wolfgang, Salzkammergut · Austria', description: 'A stiff climb (or a ride on Austria’s steepest cog railway) to a summit ledge with three lakes glittering below — the Salzkammergut in one sweep.', difficulty: 'hard', distanceKm: 10.0, elevationGainM: 1180, estimatedDurationMins: 330, tags: ['Summit', 'Lakes', 'Cog Railway', 'Views'], ecoScore: 88, weatherScore: 72, accessibilityScore: 45, transport: 'Bus + boat to St. Wolfgang', co2: 0.9, greener: ['Cog railway up, walk down'] },
  { id: 'innsbruck-nordkette', title: 'Nordkette Panorama Trail', country: 'Austria', location: 'Innsbruck, Tyrol · Austria', description: 'From the Seegrube station above Innsbruck, a balcony path along the “Jewel of the Alps” with the Inn Valley 1,500 metres below your boots.', difficulty: 'moderate', distanceKm: 6.0, elevationGainM: 300, estimatedDurationMins: 150, tags: ['Alpine', 'Cable Car', 'City Views', 'Public Transport'], ecoScore: 87, weatherScore: 74, accessibilityScore: 65, transport: 'Hungerburg funicular from town', co2: 0.3, greener: ['Funicular from the old town'] },
  { id: 'grossglockner-kaiser-franz', title: 'Kaiser-Franz-Josefs-Höhe Glacier Trails', country: 'Austria', location: 'Hohe Tauern NP · Austria', description: 'Short high-alpine trails facing Austria’s highest peak and the shrinking Pasterze glacier — marmots, ibex and a sobering climate lesson.', difficulty: 'moderate', distanceKm: 4.0, elevationGainM: 250, estimatedDurationMins: 120, tags: ['Glacier', 'Alpine', 'Wildlife', 'Views'], ecoScore: 84, weatherScore: 65, accessibilityScore: 60, transport: 'Glockner road bus (seasonal)', co2: 2.2, greener: ['Seasonal post bus from Heiligenblut'] },
  { id: 'krimml-waterfalls', title: 'Krimml Waterfalls Trail', country: 'Austria', location: 'Hohe Tauern NP · Austria', description: 'Switchbacks in the spray of Europe’s highest waterfall — 380 metres of thundering cascades with viewing ledges at every bend.', difficulty: 'moderate', distanceKm: 4.0, elevationGainM: 430, estimatedDurationMins: 150, tags: ['Waterfall', 'Family', 'Iconic', 'Spray'], ecoScore: 92, weatherScore: 80, accessibilityScore: 68, transport: 'Bus from Zell am See', co2: 0.8, greener: ['Pinzgau local railway + bus'] },
  { id: 'ahornboden-eng', title: 'Großer Ahornboden & Eng Valley', country: 'Austria', location: 'Karwendel, Tyrol · Austria', description: 'A gentle valley wander among 2,000 ancient sycamore maples beneath the Karwendel walls — pure gold in late October.', difficulty: 'easy', distanceKm: 7.0, elevationGainM: 150, estimatedDurationMins: 150, tags: ['Valley', 'Autumn Colours', 'Family', 'Alpine'], ecoScore: 93, weatherScore: 76, accessibilityScore: 75, transport: 'Seasonal Bergsteigerbus', co2: 1.1, greener: ['Bergsteigerbus from Lenggries'] },
  { id: 'wachau-heritage-trail', title: 'Wachau World Heritage Trail (Dürnstein)', country: 'Austria', location: 'Wachau, Lower Austria · Austria', description: 'Terraced vineyards, apricot orchards and the blue-towered abbey of Dürnstein, with castle ruins above the Danube where Richard the Lionheart was held.', difficulty: 'easy', distanceKm: 9.0, elevationGainM: 300, estimatedDurationMins: 180, tags: ['Vineyards', 'River', 'Heritage', 'Villages'], ecoScore: 91, weatherScore: 84, accessibilityScore: 72, transport: 'Train to Krems + bus', co2: 0.5, greener: ['Danube cycle path', 'River ferry hop'] },
  { id: 'gosausee-dachstein', title: 'Gosausee Lake Circuit', country: 'Austria', location: 'Gosau, Upper Austria · Austria', description: 'An easy loop around a mirror-still mountain lake with the glaciated Dachstein massif rising straight out of the far shore.', difficulty: 'easy', distanceKm: 4.3, elevationGainM: 80, estimatedDurationMins: 90, tags: ['Lake', 'Loop', 'Family', 'Reflections'], ecoScore: 94, weatherScore: 78, accessibilityScore: 85, transport: 'Bus from Bad Ischl', co2: 0.7, greener: ['Salzkammergut bus network'] },
  { id: 'dachstein-five-fingers', title: 'Dachstein 5fingers Viewing Platform', country: 'Austria', location: 'Obertraun, Salzkammergut · Austria', description: 'A short alpine walk from the Krippenstein cable car to a hand-shaped platform jutting over a 400-metre drop above Lake Hallstatt.', difficulty: 'easy', distanceKm: 2.5, elevationGainM: 120, estimatedDurationMins: 75, tags: ['Lookout', 'Cable Car', 'Karst', 'Views'], ecoScore: 86, weatherScore: 70, accessibilityScore: 70, transport: 'Cable car from Obertraun', co2: 0.6, greener: ['Train to Obertraun station'] },
  { id: 'salzburg-kapuzinerberg', title: 'Kapuzinerberg City Summit', country: 'Austria', location: 'Salzburg · Austria', description: 'Salzburg’s wooded city mountain: stone steps from the old town to bastion viewpoints over baroque domes and the Hohensalzburg fortress.', difficulty: 'easy', distanceKm: 4.0, elevationGainM: 220, estimatedDurationMins: 90, tags: ['City', 'Forest', 'Views', 'Public Transport'], ecoScore: 90, weatherScore: 82, accessibilityScore: 75, transport: 'On foot from the old town', co2: 0.1, greener: ['Zero-transport city hike'] },

  // ── United States ──────────────────────────────────────────────────────
  { id: 'yosemite-mist-trail', title: 'Mist Trail to Vernal Fall', country: 'United States', location: 'Yosemite NP, California · USA', description: 'Granite steps straight up through the spray of Vernal Fall — Yosemite’s signature drenching in spring, rainbows included.', difficulty: 'moderate', distanceKm: 5.4, elevationGainM: 330, estimatedDurationMins: 180, tags: ['Waterfall', 'Granite', 'Iconic', 'Spray'], ecoScore: 89, weatherScore: 84, accessibilityScore: 50, transport: 'Valley shuttle stop 16', co2: 1.6, greener: ['YARTS bus into the valley'] },
  { id: 'emerald-lake-rockies', title: 'Emerald Lake Trail', country: 'United States', location: 'Rocky Mountain NP, Colorado · USA', description: 'Three alpine lakes in five kilometres — Nymph, Dream and Emerald — each a step deeper into the cirque beneath Hallett Peak.', difficulty: 'easy', distanceKm: 5.2, elevationGainM: 200, estimatedDurationMins: 120, tags: ['Lakes', 'Alpine', 'Family', 'Views'], ecoScore: 90, weatherScore: 76, accessibilityScore: 65, transport: 'Bear Lake park shuttle', co2: 1.4, greener: ['Estes Park hiker shuttle'] },
  { id: 'delicate-arch', title: 'Delicate Arch Trail', country: 'United States', location: 'Arches NP, Utah · USA', description: 'Across bare slickrock to Utah’s free-standing icon, perched on the rim of a sandstone bowl with the La Sal Mountains behind. Magic at sunset.', difficulty: 'moderate', distanceKm: 4.8, elevationGainM: 146, estimatedDurationMins: 120, tags: ['Desert', 'Arch', 'Iconic', 'Sunset'], ecoScore: 85, weatherScore: 70, accessibilityScore: 45, transport: 'Drive from Moab', co2: 2.0, greener: ['Carpool from Moab'] },
  { id: 'grand-prismatic-overlook', title: 'Grand Prismatic Overlook Trail', country: 'United States', location: 'Yellowstone NP, Wyoming · USA', description: 'A short climb from Fairy Falls trailhead to the only place you can take in the rainbow rings of America’s largest hot spring from above.', difficulty: 'easy', distanceKm: 2.5, elevationGainM: 60, estimatedDurationMins: 60, tags: ['Geothermal', 'Lookout', 'Family', 'Iconic'], ecoScore: 87, weatherScore: 72, accessibilityScore: 70, transport: 'Drive the Grand Loop', co2: 2.6, greener: ['Guided shuttle tours'] },
  { id: 'acadia-ocean-path', title: 'Ocean Path (Thunder Hole to Otter Cliff)', country: 'United States', location: 'Acadia NP, Maine · USA', description: 'Pink granite shoreline, crashing surf at Thunder Hole and the 33-metre sea wall of Otter Cliff — Acadia’s classic easy coast walk.', difficulty: 'easy', distanceKm: 7.2, elevationGainM: 100, estimatedDurationMins: 150, tags: ['Coastal', 'Granite', 'Family', 'Public Transport'], ecoScore: 91, weatherScore: 80, accessibilityScore: 85, transport: 'Free Island Explorer bus', co2: 0.4, greener: ['Island Explorer shuttle'] },
  { id: 'multnomah-falls', title: 'Multnomah Falls & Benson Bridge', country: 'United States', location: 'Columbia River Gorge, Oregon · USA', description: 'Oregon’s tallest waterfall in two mossy tiers, crossed mid-air by Benson Bridge; continue up the switchbacks to the top platform.', difficulty: 'moderate', distanceKm: 3.8, elevationGainM: 240, estimatedDurationMins: 105, tags: ['Waterfall', 'Forest', 'Iconic', 'Public Transport'], ecoScore: 90, weatherScore: 78, accessibilityScore: 72, transport: 'Columbia Gorge Express bus', co2: 0.5, greener: ['Gorge Express from Portland'] },
  { id: 'rainier-skyline-trail', title: 'Skyline Trail Loop (Paradise)', country: 'United States', location: 'Mount Rainier NP, Washington · USA', description: 'Wildflower meadows, marmots and the great white bulk of Rainier filling the sky — the Northwest’s finest day loop from Paradise.', difficulty: 'moderate', distanceKm: 9.0, elevationGainM: 530, estimatedDurationMins: 240, tags: ['Alpine', 'Wildflowers', 'Loop', 'Glacier Views'], ecoScore: 88, weatherScore: 68, accessibilityScore: 50, transport: 'Drive to Paradise', co2: 2.4, greener: ['Carpool to Paradise'] },
  { id: 'diamond-head-summit', title: 'Diamond Head Summit Trail', country: 'United States', location: 'Honolulu, Hawaiʻi · USA', description: 'Through a volcanic crater, up a lighthouse-era staircase and out onto a bunker summit with all of Waikīkī and the Pacific below.', difficulty: 'moderate', distanceKm: 2.9, elevationGainM: 170, estimatedDurationMins: 90, tags: ['Volcano', 'City Views', 'Iconic', 'Public Transport'], ecoScore: 86, weatherScore: 92, accessibilityScore: 60, transport: 'TheBus from Waikīkī', co2: 0.3, greener: ['City bus route 23'] },
  { id: 'horseshoe-bend', title: 'Horseshoe Bend Overlook', country: 'United States', location: 'Page, Arizona · USA', description: 'A short desert walk to the rim where the Colorado River wraps a 270° emerald loop a thousand feet below. Go for golden hour.', difficulty: 'easy', distanceKm: 2.4, elevationGainM: 45, estimatedDurationMins: 45, tags: ['Desert', 'River', 'Lookout', 'Sunset'], ecoScore: 84, weatherScore: 74, accessibilityScore: 88, transport: 'Drive from Page', co2: 1.0, greener: ['Cycle from Page'] },
  { id: 'franconia-ridge-loop', title: 'Franconia Ridge Loop', country: 'United States', location: 'White Mountains, New Hampshire · USA', description: 'New England’s celebrated skywalk: up Falling Waters past three cascades, along the knife-edge alpine ridge over Lincoln and Lafayette, down past Greenleaf hut.', difficulty: 'hard', distanceKm: 14.0, elevationGainM: 1180, estimatedDurationMins: 420, tags: ['Ridge', 'Alpine', 'Loop', 'Challenging'], ecoScore: 89, weatherScore: 60, accessibilityScore: 30, transport: 'Drive to Lafayette Place', co2: 2.2, greener: ['AMC hiker shuttle'] },

  // ── Switzerland ────────────────────────────────────────────────────────
  { id: 'lauterbrunnen-valley-walk', title: 'Lauterbrunnen Valley of 72 Waterfalls', country: 'Switzerland', location: 'Bernese Oberland · Switzerland', description: 'A flat valley-floor stroll beneath overhanging cliffs where Staubbach and 71 other falls plume off the rock — Tolkien’s Rivendell in real life.', difficulty: 'easy', distanceKm: 7.0, elevationGainM: 100, estimatedDurationMins: 120, tags: ['Waterfalls', 'Valley', 'Family', 'Public Transport'], ecoScore: 95, weatherScore: 80, accessibilityScore: 90, transport: 'Train to Lauterbrunnen', co2: 0.2, greener: ['Swiss rail all the way'] },
  { id: 'oeschinensee', title: 'Oeschinensee Panorama Loop', country: 'Switzerland', location: 'Kandersteg, Bernese Oberland · Switzerland', description: 'A turquoise lake cupped by 3,000-metre walls; the balcony loop above the north shore serves the picture-book view every hundred metres.', difficulty: 'moderate', distanceKm: 8.5, elevationGainM: 480, estimatedDurationMins: 210, tags: ['Lake', 'Alpine', 'Loop', 'UNESCO'], ecoScore: 92, weatherScore: 75, accessibilityScore: 60, transport: 'Train to Kandersteg + gondola', co2: 0.3, greener: ['Rail + gondola combo'] },
  { id: 'harder-kulm', title: 'Harder Kulm — Interlaken’s Home Mountain', country: 'Switzerland', location: 'Interlaken · Switzerland', description: 'Forest switchbacks from town to the Two-Lakes-Bridge platform: Thun and Brienz lakes either side, Eiger, Mönch and Jungfrau dead ahead.', difficulty: 'moderate', distanceKm: 5.0, elevationGainM: 730, estimatedDurationMins: 180, tags: ['Lookout', 'Forest', 'Lakes', 'Public Transport'], ecoScore: 91, weatherScore: 80, accessibilityScore: 65, transport: 'On foot / funicular from Interlaken', co2: 0.1, greener: ['Walk from Interlaken Ost'] },
  { id: 'creux-du-van', title: 'Creux du Van Rock Arena', country: 'Switzerland', location: 'Val de Travers, Neuchâtel · Switzerland', description: 'Switzerland’s “Grand Canyon”: a perfect 160-metre limestone amphitheatre with ibex grazing the rim. The classic loop starts from Noiraigue station.', difficulty: 'moderate', distanceKm: 11.0, elevationGainM: 700, estimatedDurationMins: 270, tags: ['Cliffs', 'Wildlife', 'Loop', 'Public Transport'], ecoScore: 93, weatherScore: 76, accessibilityScore: 55, transport: 'Train to Noiraigue', co2: 0.2, greener: ['Rail from Neuchâtel'] },
  { id: 'aletsch-panorama', title: 'Aletsch Glacier Panorama Trail', country: 'Switzerland', location: 'Aletsch Arena, Valais · Switzerland', description: 'A high balcony path above the longest glacier in the Alps — 23 kilometres of ice streaming from the Jungfrau, UNESCO-listed and unforgettable.', difficulty: 'moderate', distanceKm: 9.0, elevationGainM: 350, estimatedDurationMins: 210, tags: ['Glacier', 'UNESCO', 'Alpine', 'Views'], ecoScore: 90, weatherScore: 72, accessibilityScore: 55, transport: 'Cable car from Fiesch/Mörel', co2: 0.4, greener: ['Rail + cable car'] },
  { id: 'first-bachalpsee', title: 'First to Bachalpsee', country: 'Switzerland', location: 'Grindelwald, Bernese Oberland · Switzerland', description: 'From the First gondola an easy alpine hour to a lake that mirrors the Schreckhorn — Switzerland’s most photographed reflection.', difficulty: 'easy', distanceKm: 6.0, elevationGainM: 160, estimatedDurationMins: 120, tags: ['Lake', 'Reflections', 'Family', 'Cable Car'], ecoScore: 90, weatherScore: 76, accessibilityScore: 75, transport: 'Gondola from Grindelwald', co2: 0.3, greener: ['Rail to Grindelwald'] },
  { id: 'gornergrat-riffelsee', title: 'Gornergrat to Riffelsee', country: 'Switzerland', location: 'Zermatt, Valais · Switzerland', description: 'Step off Europe’s highest open-air cog railway and wander down to the little lake where the Matterhorn doubles itself on still mornings.', difficulty: 'easy', distanceKm: 4.0, elevationGainM: 100, estimatedDurationMins: 90, tags: ['Matterhorn', 'Lake', 'Cog Railway', 'Iconic'], ecoScore: 89, weatherScore: 74, accessibilityScore: 70, transport: 'Gornergrat Bahn from Zermatt', co2: 0.3, greener: ['Car-free Zermatt + cog rail'] },
  { id: 'ebenalp-seealpsee', title: 'Ebenalp, Äscher Cliff & Seealpsee', country: 'Switzerland', location: 'Appenzell · Switzerland', description: 'Through prehistoric caves, past the legendary cliff-hugging Äscher guesthouse and down to the milky-green Seealpsee in the Alpstein.', difficulty: 'moderate', distanceKm: 8.0, elevationGainM: 400, estimatedDurationMins: 240, tags: ['Cliffs', 'Lake', 'Caves', 'Iconic'], ecoScore: 91, weatherScore: 74, accessibilityScore: 55, transport: 'Cable car from Wasserauen', co2: 0.3, greener: ['Appenzell railway'] },
  { id: 'lavaux-terraces', title: 'Lavaux Vineyard Terraces Walk', country: 'Switzerland', location: 'Lake Geneva, Vaud · Switzerland', description: 'A UNESCO ribbon of thousand-year-old vine terraces between Lausanne and Montreux — the lake below, the Savoy Alps across the water.', difficulty: 'easy', distanceKm: 11.0, elevationGainM: 250, estimatedDurationMins: 210, tags: ['Vineyards', 'UNESCO', 'Lake', 'Villages'], ecoScore: 94, weatherScore: 86, accessibilityScore: 80, transport: 'Train to Lutry/St-Saphorin', co2: 0.2, greener: ['Hop-on regional trains'] },
  { id: 'rigi-panorama-trail', title: 'Rigi Panorama Trail', country: 'Switzerland', location: 'Lake Lucerne · Switzerland', description: 'The “Queen of the Mountains” by boat, cogwheel and foot: a gentle high path with Lake Lucerne glittering under the whole Alpine chain.', difficulty: 'easy', distanceKm: 7.0, elevationGainM: 150, estimatedDurationMins: 135, tags: ['Panorama', 'Cog Railway', 'Family', 'Lake'], ecoScore: 92, weatherScore: 80, accessibilityScore: 82, transport: 'Boat + cog railway from Lucerne', co2: 0.3, greener: ['Steamer across Lake Lucerne'] },

  // ── France ─────────────────────────────────────────────────────────────
  { id: 'mont-saint-michel-bay', title: 'Mont-Saint-Michel Bay Crossing', country: 'France', location: 'Normandy · France', description: 'Barefoot across the sands of Europe’s greatest tidal bay to the abbey-island — with a certified guide, tides here move faster than a horse.', difficulty: 'moderate', distanceKm: 7.0, elevationGainM: 20, estimatedDurationMins: 180, tags: ['Tidal Bay', 'Heritage', 'Guided', 'Iconic'], ecoScore: 92, weatherScore: 76, accessibilityScore: 50, transport: 'Rail to Pontorson + shuttle', co2: 0.4, greener: ['TGV + navette combo'] },
  { id: 'etretat-cliffs', title: 'Étretat Chalk Cliffs & Arches', country: 'France', location: 'Normandy · France', description: 'The clifftop path over Monet’s white arches — the needle of l’Aiguille, the great arch of la Manneporte and the Alabaster Coast beyond.', difficulty: 'easy', distanceKm: 6.0, elevationGainM: 220, estimatedDurationMins: 135, tags: ['Cliffs', 'Coastal', 'Art History', 'Views'], ecoScore: 90, weatherScore: 74, accessibilityScore: 65, transport: 'Bus from Le Havre', co2: 0.5, greener: ['Train to Bréauté + bus'] },
  { id: 'cirque-de-gavarnie', title: 'Cirque de Gavarnie', country: 'France', location: 'Hautes-Pyrénées · France', description: 'A gentle valley approach into a 1,500-metre wall of rock and Europe’s tallest waterfall — Victor Hugo’s “Colosseum of nature”.', difficulty: 'easy', distanceKm: 10.0, elevationGainM: 350, estimatedDurationMins: 210, tags: ['Cirque', 'Waterfall', 'UNESCO', 'Family'], ecoScore: 93, weatherScore: 72, accessibilityScore: 70, transport: 'Bus from Lourdes (seasonal)', co2: 0.9, greener: ['Seasonal shuttle from Luz'] },
  { id: 'annecy-lakeside', title: 'Annecy Lakeside & Roc de Chère', country: 'France', location: 'Haute-Savoie · France', description: 'Europe’s cleanest lake from its wooded balcony reserve — turquoise coves, château villages and the Tournette massif across the water.', difficulty: 'easy', distanceKm: 8.0, elevationGainM: 250, estimatedDurationMins: 165, tags: ['Lake', 'Forest', 'Swimming', 'Public Transport'], ecoScore: 93, weatherScore: 84, accessibilityScore: 75, transport: 'Bus from Annecy', co2: 0.3, greener: ['Lakeshore cycle path'] },
  { id: 'chamonix-lac-blanc', title: 'Lac Blanc Balcony Trail', country: 'France', location: 'Chamonix, Haute-Savoie · France', description: 'The Aiguilles Rouges balcony to a high tarn facing the entire Mont Blanc range — arguably the finest viewpoint in the French Alps.', difficulty: 'hard', distanceKm: 10.0, elevationGainM: 900, estimatedDurationMins: 330, tags: ['Alpine', 'Lake', 'Mont Blanc', 'Challenging'], ecoScore: 89, weatherScore: 70, accessibilityScore: 35, transport: 'Chamonix valley train + lift', co2: 0.4, greener: ['Mont Blanc Express train'] },
  { id: 'colorado-provencal', title: 'Colorado Provençal Ochre Trails', country: 'France', location: 'Rustrel, Vaucluse · France', description: 'Fairy chimneys and dunes in thirty shades of orange — a former ochre quarry turned desert dreamscape in the Luberon hills.', difficulty: 'easy', distanceKm: 5.2, elevationGainM: 130, estimatedDurationMins: 105, tags: ['Ochre', 'Desert', 'Family', 'Photography'], ecoScore: 88, weatherScore: 88, accessibilityScore: 70, transport: 'Drive from Apt', co2: 1.2, greener: ['Luberon cycle loop'] },
  { id: 'dune-du-pilat', title: 'Dune du Pilat Ascent', country: 'France', location: 'Arcachon Bay, Gironde · France', description: 'Europe’s tallest sand dune — 100 metres of ridge between a pine forest and the Atlantic, with the Banc d’Arguin sandbank offshore.', difficulty: 'easy', distanceKm: 3.0, elevationGainM: 110, estimatedDurationMins: 90, tags: ['Dune', 'Coastal', 'Family', 'Sunset'], ecoScore: 87, weatherScore: 86, accessibilityScore: 60, transport: 'Bus from Arcachon station', co2: 0.4, greener: ['TER to Arcachon + bus'] },
  { id: 'puy-de-dome', title: 'Puy de Dôme — Chemin des Muletiers', country: 'France', location: 'Auvergne · France', description: 'The old mule path spirals up a UNESCO-listed volcano to a Roman temple of Mercury and a 360° chain of eighty sleeping craters.', difficulty: 'moderate', distanceKm: 6.0, elevationGainM: 400, estimatedDurationMins: 165, tags: ['Volcano', 'UNESCO', 'Panorama', 'Rack Railway'], ecoScore: 90, weatherScore: 74, accessibilityScore: 60, transport: 'Panoramique des Dômes railway', co2: 0.4, greener: ['Rack railway down'] },
  { id: 'cap-frehel-douaniers', title: 'Cap Fréhel Customs Officers’ Path', country: 'France', location: 'Côtes-d’Armor, Brittany · France', description: 'Pink sandstone cliffs, screaming seabird colonies and the fortress of La Latte on Brittany’s wild GR34 coastal path.', difficulty: 'moderate', distanceKm: 8.5, elevationGainM: 250, estimatedDurationMins: 180, tags: ['Coastal', 'Cliffs', 'Birdlife', 'GR34'], ecoScore: 92, weatherScore: 72, accessibilityScore: 55, transport: 'Bus from Saint-Malo (seasonal)', co2: 0.6, greener: ['Breizhgo coastal bus'] },
  { id: 'camargue-flamingo-trail', title: 'Camargue Flamingo Trails', country: 'France', location: 'Parc de Camargue · France', description: 'Dyke-top paths through Europe’s greatest delta: pink flamingo lagoons, white horses and black bulls between the Rhône and the sea.', difficulty: 'easy', distanceKm: 7.0, elevationGainM: 10, estimatedDurationMins: 135, tags: ['Wetlands', 'Flamingos', 'Flat', 'Birdwatching'], ecoScore: 94, weatherScore: 85, accessibilityScore: 85, transport: 'Bus from Arles', co2: 0.5, greener: ['Cycle the digue to the sea'] },

  // ── Latvia ─────────────────────────────────────────────────────────────
  { id: 'gauja-sigulda', title: 'Gauja Valley & Sigulda Castles', country: 'Latvia', location: 'Gauja NP, Sigulda · Latvia', description: 'Latvia’s “Switzerland”: sandstone cliffs, a cable car over the wooded Gauja valley and the medieval castles of Sigulda, Krimulda and Turaida.', difficulty: 'moderate', distanceKm: 10.0, elevationGainM: 200, estimatedDurationMins: 240, tags: ['Valley', 'Castles', 'Forest', 'Public Transport'], ecoScore: 93, weatherScore: 72, accessibilityScore: 70, transport: 'Train from Rīga (1h)', co2: 0.3, greener: ['Direct rail from Rīga'] },
  { id: 'kemeri-bog-boardwalk', title: 'Ķemeri Great Bog Boardwalk', country: 'Latvia', location: 'Ķemeri NP · Latvia', description: 'A boardwalk over a 8,000-year-old raised bog dotted with dark pools and dwarf pines — climb the tower for sunrise mist.', difficulty: 'easy', distanceKm: 3.4, elevationGainM: 5, estimatedDurationMins: 75, tags: ['Bog', 'Boardwalk', 'Sunrise', 'Family'], ecoScore: 96, weatherScore: 70, accessibilityScore: 88, transport: 'Train to Ķemeri', co2: 0.2, greener: ['Rīga–Tukums rail line'] },
  { id: 'jurmala-beach-walk', title: 'Jūrmala White Dune Beach Walk', country: 'Latvia', location: 'Jūrmala · Latvia', description: 'Thirty kilometres of white Baltic sand backed by pines and Art Nouveau villas — walk barefoot from Majori toward the White Dune.', difficulty: 'easy', distanceKm: 8.0, elevationGainM: 10, estimatedDurationMins: 120, tags: ['Beach', 'Flat', 'Family', 'Spa Town'], ecoScore: 91, weatherScore: 74, accessibilityScore: 92, transport: 'Train from Rīga (30min)', co2: 0.2, greener: ['Electric rail from Rīga'] },
  { id: 'cape-kolka', title: 'Cape Kolka — Meeting of Two Seas', country: 'Latvia', location: 'Slītere NP, Kurzeme · Latvia', description: 'The lonely tip of Courland where the Gulf of Rīga collides with the open Baltic in a visible line of clashing waves. Prime bird migration point.', difficulty: 'easy', distanceKm: 5.0, elevationGainM: 5, estimatedDurationMins: 105, tags: ['Cape', 'Birdwatching', 'Wild Coast', 'Remote'], ecoScore: 95, weatherScore: 68, accessibilityScore: 65, transport: 'Bus from Rīga/Talsi', co2: 1.0, greener: ['Kurzeme coastal bus'] },
  { id: 'slitere-lighthouse-trail', title: 'Slītere Lighthouse Nature Trail', country: 'Latvia', location: 'Slītere NP · Latvia', description: 'From a lighthouse on an ancient sea-cliff through wild broadleaf forest and boardwalk bog — the Baltic coast’s richest pocket of biodiversity.', difficulty: 'easy', distanceKm: 3.5, elevationGainM: 60, estimatedDurationMins: 90, tags: ['Lighthouse', 'Forest', 'Boardwalk', 'Wildlife'], ecoScore: 96, weatherScore: 70, accessibilityScore: 70, transport: 'Drive/bus via Dundaga', co2: 1.1, greener: ['Combine with Kolka bus'] },
  { id: 'ligatne-nature-trails', title: 'Līgatne Nature Trails', country: 'Latvia', location: 'Gauja NP, Līgatne · Latvia', description: 'Forest paths past large enclosures of native wildlife — brown bears, lynx, elk — plus sandstone caves and a Soviet-era secret bunker nearby.', difficulty: 'easy', distanceKm: 5.5, elevationGainM: 90, estimatedDurationMins: 135, tags: ['Wildlife', 'Forest', 'Family', 'Caves'], ecoScore: 92, weatherScore: 72, accessibilityScore: 78, transport: 'Train to Līgatne + walk', co2: 0.3, greener: ['Gauja valley rail line'] },
  { id: 'daugavas-loki', title: 'Daugavas Loki River Bends', country: 'Latvia', location: 'Latgale · Latvia', description: 'Viewpoint trails over the great protected loops of the Daugava river — nine sweeping bends of unspoiled valley in Latvia’s far southeast.', difficulty: 'easy', distanceKm: 7.0, elevationGainM: 80, estimatedDurationMins: 150, tags: ['River', 'Lookout', 'Remote', 'Nature Park'], ecoScore: 94, weatherScore: 72, accessibilityScore: 60, transport: 'Bus/drive from Daugavpils', co2: 1.2, greener: ['Regional bus to Naujene'] },
  { id: 'rundale-gardens', title: 'Rundāle Palace Gardens & Park', country: 'Latvia', location: 'Zemgale · Latvia', description: 'The “Versailles of the Baltics”: a baroque palace by Rastrelli with ten hectares of formal rose gardens and green-wall bosquets to wander.', difficulty: 'easy', distanceKm: 4.0, elevationGainM: 0, estimatedDurationMins: 120, tags: ['Palace', 'Gardens', 'Baroque', 'Family'], ecoScore: 88, weatherScore: 76, accessibilityScore: 95, transport: 'Bus from Bauska', co2: 0.8, greener: ['Rīga–Bauska bus + local hop'] },
  { id: 'kuldiga-ventas-rumba', title: 'Kuldīga & Ventas Rumba Waterfall', country: 'Latvia', location: 'Kurzeme · Latvia', description: 'Europe’s widest waterfall — 249 metres of gently spilling river — beside a UNESCO-listed old town of wooden houses and a brick bridge.', difficulty: 'easy', distanceKm: 4.5, elevationGainM: 30, estimatedDurationMins: 105, tags: ['Waterfall', 'Old Town', 'UNESCO', 'Family'], ecoScore: 92, weatherScore: 74, accessibilityScore: 90, transport: 'Bus from Rīga (2.5h)', co2: 1.0, greener: ['Intercity bus'] },
  { id: 'amata-river-trail', title: 'Amata River Sandstone Trail', country: 'Latvia', location: 'Gauja NP · Latvia', description: 'A wild riverside path beneath red Devonian sandstone outcrops like Zvārtes Rock — at its fiercest in the spring floods.', difficulty: 'moderate', distanceKm: 9.0, elevationGainM: 120, estimatedDurationMins: 210, tags: ['River', 'Sandstone', 'Wild', 'Spring Flood'], ecoScore: 95, weatherScore: 70, accessibilityScore: 55, transport: 'Train to Melturi + walk', co2: 0.3, greener: ['Cēsis rail line'] },

  // ── Belgium ────────────────────────────────────────────────────────────
  { id: 'hallerbos-bluebells', title: 'Hallerbos Bluebell Forest', country: 'Belgium', location: 'Halle, Flemish Brabant · Belgium', description: 'For two weeks each April the “Blue Forest” floor turns violet with wild hyacinths under fresh beech leaves — Belgium’s most magical walk.', difficulty: 'easy', distanceKm: 7.0, elevationGainM: 90, estimatedDurationMins: 135, tags: ['Bluebells', 'Forest', 'Spring', 'Family'], ecoScore: 94, weatherScore: 72, accessibilityScore: 80, transport: 'Train to Halle + shuttle (April)', co2: 0.3, greener: ['Seasonal bluebell shuttle'] },
  { id: 'hoge-kempen', title: 'Hoge Kempen National Park', country: 'Belgium', location: 'Limburg · Belgium', description: 'Purple heather plains, pine woods and mine-era lakes in Belgium’s first national park — climb the terril for views to the Meuse.', difficulty: 'easy', distanceKm: 9.0, elevationGainM: 100, estimatedDurationMins: 180, tags: ['Heathland', 'Lakes', 'Cycling Junctions', 'Family'], ecoScore: 93, weatherScore: 72, accessibilityScore: 75, transport: 'Bus from Genk', co2: 0.4, greener: ['Limburg cycle-node network'] },
  { id: 'ninglinspo-valley', title: 'Ninglinspo Wild Stream Valley', country: 'Belgium', location: 'Aywaille, Ardennes · Belgium', description: 'Belgium’s only true mountain stream: a rooty, rocky scramble past chained cascades and bathing pots carved into pink quartzite.', difficulty: 'moderate', distanceKm: 7.5, elevationGainM: 250, estimatedDurationMins: 180, tags: ['Stream', 'Cascades', 'Ardennes', 'Adventure'], ecoScore: 93, weatherScore: 70, accessibilityScore: 40, transport: 'Train to Aywaille + walk', co2: 0.3, greener: ['Liège–Aywaille rail'] },
  { id: 'tombeau-du-geant', title: 'Tombeau du Géant Viewpoint Loop', country: 'Belgium', location: 'Bouillon, Ardennes · Belgium', description: 'The Semois river wraps a wooded hill so perfectly it looks placed by hand — the Ardennes’ most famous panorama, best in morning mist.', difficulty: 'moderate', distanceKm: 8.0, elevationGainM: 220, estimatedDurationMins: 180, tags: ['River Bend', 'Lookout', 'Forest', 'Mist'], ecoScore: 94, weatherScore: 70, accessibilityScore: 55, transport: 'Bus from Bouillon', co2: 0.9, greener: ['TEC bus from Libramont rail'] },
  { id: 'hautes-fagnes-boardwalk', title: 'Hautes Fagnes High Fens Boardwalks', country: 'Belgium', location: 'Eifel NP, Liège · Belgium', description: 'Belgium’s rooftop: raised-bog boardwalks across misty moorland at 694 m, snowshoe country in winter and cotton-grass white in June.', difficulty: 'easy', distanceKm: 8.0, elevationGainM: 60, estimatedDurationMins: 150, tags: ['Bog', 'Boardwalk', 'Moorland', 'Snowshoe'], ecoScore: 95, weatherScore: 62, accessibilityScore: 78, transport: 'Bus from Eupen/Verviers', co2: 0.5, greener: ['Vennbahn rail-trail by bike'] },
  { id: 'bruges-canal-walk', title: 'Bruges Canals & Windmill Ramparts', country: 'Belgium', location: 'Bruges, West Flanders · Belgium', description: 'Swans on the Minnewater, medieval quays and a green rampart ring of four surviving windmills circling the World Heritage old town.', difficulty: 'easy', distanceKm: 6.5, elevationGainM: 20, estimatedDurationMins: 120, tags: ['Canals', 'Heritage', 'City', 'Windmills'], ecoScore: 90, weatherScore: 72, accessibilityScore: 92, transport: 'Train to Bruges', co2: 0.2, greener: ['Direct IC rail'] },
  { id: 'dinant-citadel-meuse', title: 'Dinant Citadel & Meuse Cliffs', country: 'Belgium', location: 'Dinant, Namur · Belgium', description: '408 steps up the cliff-face to the citadel above the onion-domed collegiate church, then rampart paths high over the Meuse valley.', difficulty: 'moderate', distanceKm: 5.0, elevationGainM: 180, estimatedDurationMins: 120, tags: ['Citadel', 'River', 'Cliffs', 'Heritage'], ecoScore: 89, weatherScore: 72, accessibilityScore: 60, transport: 'Train to Dinant', co2: 0.3, greener: ['Namur–Dinant rail along the Meuse'] },
  { id: 'zwin-nature-park', title: 'Zwin Nature Park — Bird Airport', country: 'Belgium', location: 'Knokke-Heist · Belgium', description: 'Tidal salt-marsh lagoons on the Dutch border where storks nest on the visitor centre and waders refuel on the East Atlantic flyway.', difficulty: 'easy', distanceKm: 6.0, elevationGainM: 5, estimatedDurationMins: 135, tags: ['Birdwatching', 'Salt Marsh', 'Coastal', 'Family'], ecoScore: 95, weatherScore: 70, accessibilityScore: 85, transport: 'Coast tram + bus to Knokke', co2: 0.3, greener: ['Kusttram along the coast'] },
  { id: 'sonian-forest', title: 'Sonian Forest Beech Cathedral', country: 'Belgium', location: 'Brussels · Belgium', description: 'A UNESCO-listed cathedral of 200-year-old beeches on the capital’s doorstep — arboretum groves, ponds and endless smooth grey pillars.', difficulty: 'easy', distanceKm: 9.0, elevationGainM: 110, estimatedDurationMins: 165, tags: ['Beech Forest', 'UNESCO', 'City Escape', 'Family'], ecoScore: 93, weatherScore: 72, accessibilityScore: 82, transport: 'Brussels tram/metro to the edge', co2: 0.1, greener: ['Tram 44 heritage line'] },
  { id: 'durbuy-ourthe-trail', title: 'Durbuy & Ourthe Valley Trail', country: 'Belgium', location: 'Durbuy, Luxembourg province · Belgium', description: 'From the “smallest town in the world”, riverside and ridgeline paths past the folded anticline rock and topiary gardens of the Ourthe valley.', difficulty: 'moderate', distanceKm: 8.5, elevationGainM: 240, estimatedDurationMins: 180, tags: ['River', 'Old Town', 'Ardennes', 'Views'], ecoScore: 92, weatherScore: 72, accessibilityScore: 62, transport: 'Train to Barvaux + walk', co2: 0.4, greener: ['Ourthe valley rail'] },

  // ── Norway ─────────────────────────────────────────────────────────────
  { id: 'besseggen-ridge', title: 'Besseggen Ridge', country: 'Norway', location: 'Jotunheimen NP · Norway', description: 'Norway’s most famous day hike: the knife ridge between emerald Gjende and deep-blue Bessvatnet, immortalised by Ibsen’s Peer Gynt.', difficulty: 'hard', distanceKm: 14.0, elevationGainM: 1100, estimatedDurationMins: 420, tags: ['Ridge', 'Two Lakes', 'Iconic', 'Challenging'], ecoScore: 91, weatherScore: 62, accessibilityScore: 30, transport: 'Boat from Gjendesheim', co2: 1.2, greener: ['Gjende electric ferry'] },
  { id: 'romsdalseggen', title: 'Romsdalseggen Ridge', country: 'Norway', location: 'Åndalsnes, Romsdal · Norway', description: 'Called Norway’s most beautiful ridge walk — a sky-line traverse above the Rauma valley facing the Troll Wall, ending at the town stairs.', difficulty: 'hard', distanceKm: 10.3, elevationGainM: 970, estimatedDurationMins: 420, tags: ['Ridge', 'Fjord Views', 'Challenging', 'Bus Access'], ecoScore: 90, weatherScore: 60, accessibilityScore: 28, transport: 'Hiker bus from Åndalsnes', co2: 0.8, greener: ['Rauma railway to town'] },
  { id: 'galdhopiggen', title: 'Galdhøpiggen — Roof of Norway', country: 'Norway', location: 'Jotunheimen NP · Norway', description: 'Northern Europe’s highest summit at 2,469 m: a guided rope crossing of the Styggebreen glacier, then scree to a hut on the very top.', difficulty: 'hard', distanceKm: 11.0, elevationGainM: 1000, estimatedDurationMins: 420, tags: ['Summit', 'Glacier', 'Guided', 'Highest Peak'], ecoScore: 88, weatherScore: 58, accessibilityScore: 25, transport: 'Drive/bus to Juvasshytta', co2: 1.6, greener: ['Valdresekspressen bus'] },
  { id: 'lofoten-reinebringen', title: 'Reinebringen Stairs', country: 'Norway', location: 'Lofoten Islands · Norway', description: '1,978 Sherpa-built stone steps to THE Lofoten view: Reine’s red rorbu cabins scattered over turquoise water beneath granite spires.', difficulty: 'moderate', distanceKm: 3.0, elevationGainM: 450, estimatedDurationMins: 150, tags: ['Stairs', 'Fjord', 'Iconic', 'Islands'], ecoScore: 89, weatherScore: 60, accessibilityScore: 40, transport: 'Bus along the E10 to Reine', co2: 0.9, greener: ['Lofoten express bus'] },
  { id: 'geiranger-skagefla', title: 'Skageflå Farm above Geirangerfjord', country: 'Norway', location: 'Geiranger · Norway', description: 'Boat in beneath the Seven Sisters falls, then climb to an abandoned shelf farm 250 m above the UNESCO fjord and walk out high.', difficulty: 'moderate', distanceKm: 8.0, elevationGainM: 500, estimatedDurationMins: 270, tags: ['Fjord', 'UNESCO', 'Waterfalls', 'Boat Access'], ecoScore: 92, weatherScore: 66, accessibilityScore: 35, transport: 'Sightseeing boat drop-off', co2: 1.0, greener: ['Electric fjord boat'] },
  { id: 'aurlandsdalen', title: 'Aurlandsdalen Valley', country: 'Norway', location: 'Aurland, Vestland · Norway', description: '“Norway’s Grand Canyon” — a historic path from Østerbø down a wild gorge of waterfalls and cliff farms to the fjord at Vassbygdi.', difficulty: 'moderate', distanceKm: 20.0, elevationGainM: 300, estimatedDurationMins: 390, tags: ['Gorge', 'Historic Route', 'Waterfalls', 'Point-to-Point'], ecoScore: 93, weatherScore: 68, accessibilityScore: 35, transport: 'Bus from Flåm/Aurland', co2: 0.7, greener: ['Flåm railway + local bus'] },
  { id: 'kjeragbolten', title: 'Kjeragbolten Boulder', country: 'Norway', location: 'Lysefjord, Rogaland · Norway', description: 'Chain-assisted slabs to the boulder wedged in a crack 984 metres above Lysefjord — Norway’s boldest photo stop, knees optional.', difficulty: 'hard', distanceKm: 11.0, elevationGainM: 800, estimatedDurationMins: 360, tags: ['Boulder', 'Fjord', 'Chains', 'Adrenaline'], ecoScore: 87, weatherScore: 60, accessibilityScore: 22, transport: 'Seasonal bus from Stavanger', co2: 1.5, greener: ['Lysevegen shuttle bus'] },
  { id: 'dovrefjell-snohetta', title: 'Snøhetta Viewpoint — Wild Reindeer Pavilion', country: 'Norway', location: 'Dovrefjell NP · Norway', description: 'An easy mountain-plateau walk to the award-winning wooden pavilion facing Snøhetta — scan the tundra for wild reindeer and musk oxen.', difficulty: 'easy', distanceKm: 3.0, elevationGainM: 150, estimatedDurationMins: 90, tags: ['Plateau', 'Musk Ox', 'Architecture', 'Family'], ecoScore: 94, weatherScore: 64, accessibilityScore: 70, transport: 'Train to Hjerkinn (Dovre line)', co2: 0.3, greener: ['Dovrebanen railway'] },
  { id: 'senja-segla', title: 'Segla Peak, Senja', country: 'Norway', location: 'Senja, Troms · Norway', description: 'The sail-shaped horn of Arctic Norway: a steep grind from Fjordgård to a summit ridge that drops 600 m sheer into Mefjord.', difficulty: 'hard', distanceKm: 5.4, elevationGainM: 600, estimatedDurationMins: 240, tags: ['Peak', 'Arctic', 'Fjord', 'Midnight Sun'], ecoScore: 90, weatherScore: 58, accessibilityScore: 28, transport: 'Drive/boat to Fjordgård', co2: 1.8, greener: ['Summer boat from Tromsø'] },
  { id: 'flam-brekkefossen', title: 'Brekkefossen Waterfall above Flåm', country: 'Norway', location: 'Flåm, Aurlandsfjord · Norway', description: 'A short, steep stair-climb from the fjord village to a waterfall ledge with the whole green Flåm valley and Aurlandsfjord at your feet.', difficulty: 'moderate', distanceKm: 3.0, elevationGainM: 250, estimatedDurationMins: 105, tags: ['Waterfall', 'Fjord', 'Short & Steep', 'Rail Access'], ecoScore: 92, weatherScore: 66, accessibilityScore: 55, transport: 'Flåm railway terminus', co2: 0.3, greener: ['Flåmsbana scenic railway'] },

  // ── United Kingdom ─────────────────────────────────────────────────────
  { id: 'scafell-pike', title: 'Scafell Pike from Wasdale', country: 'United Kingdom', location: 'Lake District, England · UK', description: 'England’s highest ground by the classic Wasdale route — a rocky grind rewarded with a summit cairn view across the whole Lakeland fell country.', difficulty: 'hard', distanceKm: 9.0, elevationGainM: 900, estimatedDurationMins: 330, tags: ['Summit', 'Highest Peak', 'Fells', 'Challenging'], ecoScore: 89, weatherScore: 55, accessibilityScore: 30, transport: 'Drive to Wasdale Head', co2: 2.0, greener: ['Base in Keswick, shared lift'] },
  { id: 'snowdon-llanberis', title: 'Snowdon (Yr Wyddfa) — Llanberis Path', country: 'United Kingdom', location: 'Eryri (Snowdonia), Wales · UK', description: 'The gentlest way up Wales’ highest mountain, shadowing the rack railway to a summit that on clear days sees Ireland.', difficulty: 'hard', distanceKm: 14.5, elevationGainM: 950, estimatedDurationMins: 360, tags: ['Summit', 'Railway', 'Iconic', 'Wales'], ecoScore: 88, weatherScore: 55, accessibilityScore: 45, transport: 'Sherpa’r Wyddfa bus network', co2: 0.6, greener: ['Snowdon Sherpa buses'] },
  { id: 'ben-nevis-track', title: 'Ben Nevis Mountain Track', country: 'United Kingdom', location: 'Lochaber, Scotland · UK', description: 'The UK’s roof at 1,345 m: a relentless stone staircase from Glen Nevis into the clouds, past the ruins of the old summit observatory.', difficulty: 'hard', distanceKm: 17.0, elevationGainM: 1330, estimatedDurationMins: 450, tags: ['Summit', 'Highest Peak', 'Scotland', 'Challenging'], ecoScore: 87, weatherScore: 50, accessibilityScore: 28, transport: 'Bus/walk from Fort William', co2: 0.4, greener: ['Caledonian Sleeper to Fort William'] },
  { id: 'seven-sisters-cliffs', title: 'Seven Sisters Chalk Cliffs', country: 'United Kingdom', location: 'East Sussex, England · UK', description: 'The rollercoaster of brilliant white chalk between Cuckmere Haven and Birling Gap — England’s south coast at its most cinematic.', difficulty: 'moderate', distanceKm: 10.0, elevationGainM: 350, estimatedDurationMins: 210, tags: ['Chalk Cliffs', 'Coastal', 'South Downs', 'Views'], ecoScore: 91, weatherScore: 70, accessibilityScore: 60, transport: 'Bus 12X from Brighton/Eastbourne', co2: 0.4, greener: ['Coaster bus along the A259'] },
  { id: 'giants-causeway-path', title: 'Giant’s Causeway Cliff Path', country: 'United Kingdom', location: 'County Antrim, Northern Ireland · UK', description: '40,000 basalt columns stepping into the Atlantic, framed by the red cliff route past the Organ Pipes and the Chimney Stacks.', difficulty: 'easy', distanceKm: 5.0, elevationGainM: 150, estimatedDurationMins: 120, tags: ['Basalt', 'UNESCO', 'Coastal', 'Legend'], ecoScore: 90, weatherScore: 62, accessibilityScore: 70, transport: 'Causeway Rambler bus', co2: 0.5, greener: ['Translink Rambler service'] },
  { id: 'cat-bells-keswick', title: 'Cat Bells above Derwentwater', country: 'United Kingdom', location: 'Lake District, England · UK', description: 'Everybody’s first Lakeland fell: a short scrambly ridge with Derwentwater, Keswick and Skiddaw arranged perfectly below.', difficulty: 'moderate', distanceKm: 5.5, elevationGainM: 400, estimatedDurationMins: 150, tags: ['Fell', 'Lake Views', 'Family', 'Boat Access'], ecoScore: 92, weatherScore: 60, accessibilityScore: 55, transport: 'Keswick launch to Hawes End', co2: 0.3, greener: ['Derwentwater launch boat'] },
  { id: 'quiraing-skye', title: 'The Quiraing Circuit', country: 'United Kingdom', location: 'Isle of Skye, Scotland · UK', description: 'A landslip dreamscape of pinnacles, hidden plateaus and cliffs on Skye’s Trotternish ridge — otherworldly in any weather, and there will be weather.', difficulty: 'moderate', distanceKm: 6.8, elevationGainM: 300, estimatedDurationMins: 180, tags: ['Landslip', 'Pinnacles', 'Skye', 'Photography'], ecoScore: 91, weatherScore: 52, accessibilityScore: 40, transport: 'Drive/bus from Portree', co2: 1.4, greener: ['Stagecoach 57 loop service'] },
  { id: 'malham-cove', title: 'Malham Cove & Gordale Scar', country: 'United Kingdom', location: 'Yorkshire Dales, England · UK', description: 'A 70-metre limestone amphitheatre with a cracked pavement on top, then the hidden waterfall gorge of Gordale Scar and Janet’s Foss.', difficulty: 'moderate', distanceKm: 8.0, elevationGainM: 260, estimatedDurationMins: 180, tags: ['Limestone', 'Gorge', 'Waterfall', 'Loop'], ecoScore: 92, weatherScore: 62, accessibilityScore: 58, transport: 'Bus from Skipton (seasonal)', co2: 0.5, greener: ['DalesBus network'] },
  { id: 'durdle-door-coast', title: 'Durdle Door & Lulworth Cove', country: 'United Kingdom', location: 'Jurassic Coast, Dorset · UK', description: 'Over the headland between a perfect scallop-shell cove and the great limestone arch of Durdle Door on England’s only natural World Heritage coast.', difficulty: 'moderate', distanceKm: 5.5, elevationGainM: 220, estimatedDurationMins: 135, tags: ['Arch', 'Cove', 'UNESCO', 'Beaches'], ecoScore: 90, weatherScore: 72, accessibilityScore: 55, transport: 'Bus from Wool station', co2: 0.4, greener: ['Jurassic Coaster bus'] },
  { id: 'hadrians-wall-housesteads', title: 'Hadrian’s Wall — Housesteads to Sycamore Gap', country: 'United Kingdom', location: 'Northumberland, England · UK', description: 'The wildest surviving stretch of Rome’s northern frontier, striding the Whin Sill crags from Housesteads fort past crag-top milecastles.', difficulty: 'moderate', distanceKm: 8.5, elevationGainM: 250, estimatedDurationMins: 180, tags: ['Roman', 'Heritage', 'Crags', 'History'], ecoScore: 91, weatherScore: 58, accessibilityScore: 55, transport: 'AD122 Hadrian’s Wall bus', co2: 0.5, greener: ['AD122 seasonal bus'] },
];

/** Upsert every curated route (assumes an open mongoose connection). */
async function upsertCuratedRoutes() {
  let upserts = 0;
  for (let i = 0; i < SEEDS.length; i++) {
    const s = SEEDS[i];
    const coord = COORDS[s.id];
    const geometry = coord ? makeLine(coord, s.id) : undefined;
    const doc = {
      slug: s.id,
      type: 'curated',
      title: s.title,
      country: s.country,
      location: s.location,
      description: s.description,
      difficulty: s.difficulty,
      distanceKm: s.distanceKm,
      elevationGainM: s.elevationGainM,
      estimatedDurationMins: s.estimatedDurationMins,
      // Real place photo first; scenic pool image as the secondary gallery shot.
      photos: PHOTOS[s.id] ? [PHOTOS[s.id], IMG[i % IMG.length]] : img(i),
      tags: s.tags,
      ecoScore: s.ecoScore,
      weatherScore: s.weatherScore,
      accessibilityScore: s.accessibilityScore,
      ecoImpact: { transportMode: s.transport, co2EstimateKg: s.co2, greenerAlternatives: s.greener },
      geometry,
      startPoint: coord ? { type: 'Point', coordinates: [coord[1], coord[0]] } : undefined,
      creatorName: 'Dayla',
      moderation: { status: 'approved', reports: [] },
      seedVersion: SEED_VERSION,
    };
    // Upsert by slug; never clobber engagement (savedBy/votes/comments) on re-seed.
    await Route.findOneAndUpdate({ slug: s.id }, { $set: doc }, { upsert: true, new: true, setDefaultsOnInsert: true });
    upserts += 1;
  }
  return upserts;
}

/**
 * Boot-time guard: seed when the curated catalogue is missing OR stale (older
 * seedVersion), so fresh databases self-populate and content updates (e.g. the
 * real place photos) roll out without shell access. Fast no-op otherwise.
 */
async function ensureCuratedRoutes() {
  const current = await Route.countDocuments({ type: 'curated', seedVersion: SEED_VERSION });
  if (current >= SEEDS.length) return 0;
  return upsertCuratedRoutes();
}

module.exports = { upsertCuratedRoutes, ensureCuratedRoutes };

// CLI: node backend/scripts/seed-routes.js  (forces a full upsert)
if (require.main === module) {
  (async () => {
    try {
      await connectDB();
      const upserts = await upsertCuratedRoutes();
      console.log(`Seeded/updated ${upserts} curated routes.`);
      await mongoose.connection.close();
      process.exit(0);
    } catch (err) {
      console.error('Seed failed:', err);
      process.exit(1);
    }
  })();
}
